//
//  NotificationDelegate.swift
//  GeoTrackAssignment
//
//  Created by Raman kumar on 20/08/26.
//


import Foundation
import UserNotifications
import UIKit

/// Handles notification events received by the application.
///
/// `NotificationDelegate` is responsible for:
/// - Displaying notifications while the app is in the foreground.
/// - Handling user interaction with notifications.
/// - Clearing the application icon badge when a notification is opened.
///
/// The delegate is implemented as a shared singleton so the same
/// instance can be assigned to `UNUserNotificationCenter`.
public final class NotificationDelegate: NSObject,
                                         UNUserNotificationCenterDelegate {

    // MARK: - Singleton

    /// Shared notification delegate instance.
    public static let shared = NotificationDelegate()

    /// Prevents creation of additional delegate instances.
    private override init() {
        super.init()
    }

    // MARK: - Foreground Notification

    /// Determines how a notification should be presented while the
    /// application is running in the foreground.
    ///
    /// By default, iOS may not display a notification banner when the
    /// application is in the foreground. Returning `.banner`, `.sound`,
    /// and `.badge` explicitly enables those presentation options.
    ///
    /// - Parameters:
    ///   - center: Notification center delivering the notification.
    ///   - notification: Notification that was received.
    ///
    /// - Returns: Presentation options for the notification.
    public func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification
    ) async -> UNNotificationPresentationOptions {

        logForegroundNotification(notification)

        return [
            .banner,
            .sound,
            .badge
        ]
    }

    // MARK: - Notification Interaction

    /// Handles a user's interaction with a delivered notification.
    ///
    /// When the user taps a notification, the application badge is
    /// cleared.
    ///
    /// - Parameters:
    ///   - center: Notification center that received the response.
    ///   - response: User's notification response.
    public func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        didReceive response: UNNotificationResponse
    ) async {

        logNotificationInteraction(response)

        await clearBadge()
    }

    // MARK: - Badge

    /// Clears the application's notification badge.
    ///
    /// `UIApplication` is accessed on the main actor because it is
    /// UIKit application state.
    private func clearBadge() async {

        await MainActor.run {
            UIApplication.shared.applicationIconBadgeNumber = 0
        }

        print("[NotificationDelegate] Badge cleared")
    }

    // MARK: - Logging

    /// Logs a foreground notification event.
    ///
    /// - Parameter notification: Notification received by the app.
    private func logForegroundNotification(
        _ notification: UNNotification
    ) {

        let identifier =
            notification.request.identifier

        print(
            """
            [NotificationDelegate]
            Foreground notification received.
            identifier=\(identifier)
            """
        )
    }

    /// Logs notification interaction.
    ///
    /// - Parameter response: Notification response generated by the user.
    private func logNotificationInteraction(
        _ response: UNNotificationResponse
    ) {

        let identifier =
            response.notification.request.identifier

        print(
            """
            [NotificationDelegate]
            Notification opened.
            identifier=\(identifier)
            action=\(response.actionIdentifier)
            """
        )
    }
}
